server:
  port: 8088


spring:
  application:
    name: 大数据风控芝麻信用接口
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  datasource:
    name: mybatis-page-help
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://138.138.81.160:3306/channel?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  typeAliasesPackage: com.allinpay.wjt.model
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:mybatis/mybatis-config.xml
